{
 "title": "WAB4-Grafana-Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pods Running",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prototype\", phase=\"Running\", pod=~\"server-.*\"})"
    }
   ]
  },
  {
   "title": "Current Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"prototype\", phase=\"Running\", pod=~\"server-.*\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas (desired vs available)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"prototype\", deployment=\"server\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"prototype\", deployment=\"server\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=~\"prototype\", deployment=\"server\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Pod Restarts (last 10min)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=\"prototype\", pod=~\"server-.*\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restarts (last 10min)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=\"prototype\", pod=~\"server-.*\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKilled Events (all pods)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(node_vmstat_oom_kill{namespace=\"monitoring\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"prototype\", pod=~\"server-.*\", resource=\"cpu\"} * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"prototype\", pod=~\"server-.*\", resource=\"memory\", unit=\"byte\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"prototype\", pod=~\"server.*\"}[2m]) * 500",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"prototype\", pod=~\"server-.*\", container!=\"POD\"} / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}