apiVersion: batch/v1
kind: Job
metadata:
  name: k6-mem
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6","run","/scripts/mem.js"]
          env:
            - name: BASE_URL
              value: http://app:3000
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: k6-scripts
            items:
              - key: mem.js
                path: mem.js